//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_tareaEntities : DbContext
    {
        public db_tareaEntities()
            : base("name=db_tareaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<horario> horarios { get; set; }
        public virtual DbSet<pedido> pedidoes { get; set; }
        public virtual DbSet<producto> productoes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
