//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<decimal> precio_venta { get; set; }
        public Nullable<int> cantidad_disponible { get; set; }
        public Nullable<int> activo { get; set; }
        public int id_pedido { get; set; }
    
        public virtual horario horario { get; set; }
        public virtual producto producto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
