//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fecha_naciminetp { get; set; }
        public Nullable<bool> actvio { get; set; }
    
        public virtual pedidod pedidod { get; set; }
    }
}
